/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as BioSlugIndexRouteImport } from './routes/bio.$slug.index'
import { Route as BioSlugSrcRouteImport } from './routes/bio.$slug.$src'
import { Route as OutSlugDspSrcRouteImport } from './routes/out.$slug.$dsp.$src'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const BioSlugIndexRoute = BioSlugIndexRouteImport.update({
  id: '/bio/$slug/',
  path: '/bio/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const BioSlugSrcRoute = BioSlugSrcRouteImport.update({
  id: '/bio/$slug/$src',
  path: '/bio/$slug/$src',
  getParentRoute: () => rootRouteImport,
} as any)
const OutSlugDspSrcRoute = OutSlugDspSrcRouteImport.update({
  id: '/out/$slug/$dsp/$src',
  path: '/out/$slug/$dsp/$src',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manifesto': typeof ManifestoRoute
  '/bio/$slug/$src': typeof BioSlugSrcRoute
  '/bio/$slug/': typeof BioSlugIndexRoute
  '/out/$slug/$dsp/$src': typeof OutSlugDspSrcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manifesto': typeof ManifestoRoute
  '/bio/$slug/$src': typeof BioSlugSrcRoute
  '/bio/$slug': typeof BioSlugIndexRoute
  '/out/$slug/$dsp/$src': typeof OutSlugDspSrcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manifesto': typeof ManifestoRoute
  '/bio/$slug/$src': typeof BioSlugSrcRoute
  '/bio/$slug/': typeof BioSlugIndexRoute
  '/out/$slug/$dsp/$src': typeof OutSlugDspSrcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manifesto'
    | '/bio/$slug/$src'
    | '/bio/$slug/'
    | '/out/$slug/$dsp/$src'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manifesto'
    | '/bio/$slug/$src'
    | '/bio/$slug'
    | '/out/$slug/$dsp/$src'
  id:
    | '__root__'
    | '/'
    | '/manifesto'
    | '/bio/$slug/$src'
    | '/bio/$slug/'
    | '/out/$slug/$dsp/$src'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManifestoRoute: typeof ManifestoRoute
  BioSlugSrcRoute: typeof BioSlugSrcRoute
  BioSlugIndexRoute: typeof BioSlugIndexRoute
  OutSlugDspSrcRoute: typeof OutSlugDspSrcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bio/$slug/': {
      id: '/bio/$slug/'
      path: '/bio/$slug'
      fullPath: '/bio/$slug/'
      preLoaderRoute: typeof BioSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bio/$slug/$src': {
      id: '/bio/$slug/$src'
      path: '/bio/$slug/$src'
      fullPath: '/bio/$slug/$src'
      preLoaderRoute: typeof BioSlugSrcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/out/$slug/$dsp/$src': {
      id: '/out/$slug/$dsp/$src'
      path: '/out/$slug/$dsp/$src'
      fullPath: '/out/$slug/$dsp/$src'
      preLoaderRoute: typeof OutSlugDspSrcRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManifestoRoute: ManifestoRoute,
  BioSlugSrcRoute: BioSlugSrcRoute,
  BioSlugIndexRoute: BioSlugIndexRoute,
  OutSlugDspSrcRoute: OutSlugDspSrcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
